<div id="dtlms-course-curriculum-popup" class="dtlms-course-curriculum-popup-quiz"><div class="dtlms-course-curriculum-popup-header" style="background-image:url(https://dtlmselementor.wpengine.com/wp-content/uploads/2016/09/Quiz-image-8.jpg);"><div class="dtlms-curriculum-intro"><div class="dtlms-column dtlms-one-column first"><div class="dtlms-curriculum-intro-details"><h2>Questions With Images</h2><div class="dtlms-curriculum-intro-details-meta"><span class="dtlms-curriculum-duration">20 hrs </span></div></div><h3>Sed quia consequuntur</h3></div></div><div class="dtlms-refresh-course-curriculum"></div><div class="dtlms-close-course-curriculum-popup"></div></div><div class="dtlms-course-curriculum-popup-container"><div class="dtlms-column dtlms-one-fifth first"><div class="dtlms-curriculum-details"><div class="dtlms-curriculum-detailed-links"><div class="dtlms-course-curriculum-toggle-group-holder"><div class="dtlms-toggle-group-set">
		        			<div class="dtlms-toggle-content" style="display: block;">
		        				<div class="block">
		        					<ul class="dtlms-curriculum-list "><li class=" preview-item purchased-item"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-book"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="-1"  data-curriculumid="6071">Aliquam massa turpis</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-preview">Preview</div><div class="dtlms-curriculum-meta-duration"><span>2 hrs </span></div></div></li><li class=" preview-item purchased-item"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-book"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="-1"  data-curriculumid="6070">Cras pharetra nisl et magna</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-preview">Preview</div><div class="dtlms-curriculum-meta-duration"><span>30 mins </span></div></div></li><li class=" purchased-item"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-book"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="-1"  data-curriculumid="6068">Nullam vestibulum eros</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-duration"><span>20 mins </span></div></div></li><li class=" preview-item purchased-item"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-book"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="-1"  data-curriculumid="6065">Placerat odio eu</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-preview">Preview</div><div class="dtlms-curriculum-meta-duration"><span>2 hrs </span></div></div></li><li class=" purchased-item"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-book"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="-1"  data-curriculumid="6063">Aliquam dolor non</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-duration"><span>30 mins </span></div></div><div class="dtlms-toggle-group-set">
		        			<div class="dtlms-toggle-content" style="display: block;">
		        				<div class="block">
		        					<ul class="dtlms-curriculum-list"><li class=" preview-item purchased-item"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-pen-square"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="6063"  data-curriculumid="7047">Fill In The Blank Questions</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-preview">Preview</div><div class="dtlms-curriculum-meta-duration"><span>30 mins </span></div></div></li></div></div></div></li><li class=" preview-item purchased-item active"><div class="dtlms-curriculum-meta-icon"><span class="fas fa-pen-square"></span></div><div class="dtlms-curriculum-meta-title"><a href="#" onclick="return false;" data-courseid="19320" data-parentcurriculumid="-1"  data-curriculumid="88">Questions With Images</a></div><div class="dtlms-curriculum-meta-items"><div class="dtlms-curriculum-meta-preview">Preview</div><div class="dtlms-curriculum-meta-duration"><span>20 hrs </span></div></div></li></ul></div></div></div></div></div></div></div><div class="dtlms-column dtlms-four-fifth"><div class="dtlms-curriculum-content-holder"><div class="dtlms-quiz-details-container">Nemo enim ipsam voluptatem quia voluptas sit atur aut odit aut fugit, sed quia consequuntur magni res.Nemo enim ipsam voluptatem quia voluptas sit atur aut odit aut fugit, sed quia consequuntur magni res.
Nemo enim ipsam voluptatem quia voluptas sit atur aut odit aut fugit, sed quia consequuntur magni res.Nemo enim ipsam voluptatem quia voluptas sit atur aut odit aut fugit, sed quia consequuntur magni res.<ul class="dtlms-quiz-features-list"><li><label><i class="fab fa-gg"></i>Total Attempts Allowed</label> <span> 1000</span> </li><li><label><i class="fab fa-gg-circle"></i>Total Attempts Remaining</label> <span> 1000</span> </li><li><label><i class="far fa-clock"></i>Duration</label> <span> 20 hours </span> </li><li><label><i class="fas fa-question-circle"></i>Question Categories</label> <span> Questions With Images</span> </li><li><label><i class="far fa-question-circle"></i>Total Questions</label> <span> 9</span> </li><li><label><i class="fas fa-marker"></i>Total Marks</label> <span> 90</span> </li></ul><div class="dtlms-info-box"><strong>Note: </strong>You have to complete the quiz in 20 hours . Timer will be triggered once you press the &quot;Start Quiz&quot; button.</div><a class="dtlms-button large filled" id="dtlms-start-quiz" onclick="return false;" data-startquiz-nonce="7c58c6cd0a" data-courseid="19320" data-userid="74"  data-lessonid="-1" data-quizid="88" data-assignmentid="-1" data-authorid="1" data-parentcurriculumid="-1">Start Quiz</a></div></div></div><div id="dtlms-ajax-load-image"  style="display:none;">
					<div class="dtlms-loader-inner">
						<div class="dtlms-loading"></div>
						<div class="dtlms-pad">
							<div class="dtlms-line dtlms-line1"></div>
							<div class="dtlms-line dtlms-line2"></div>
							<div class="dtlms-line dtlms-line3"></div>
						</div>
					</div>
				</div></div></div>